
import sys
import os

# Parametric Frisbee Drone Generator
def generate_frisbee_drone_scad(radius=150, height=20, wall_thick=2):
    """
    Generates OpenSCAD code for a Monocoque Frisbee Drone.
    Units: mm
    """
    code = f"""// BRICK OS - Frisbee Drone Geometry
// Generated by OpenSCADAgent
// Regime: Experimental | Environment: Earth | Payload: 0.5kg

$fn = 64; // High resolution for curves

// --- Parameters ---
outer_radius = {radius};
hub_radius = 40;
rim_height = {height};
airfoil_thickness = 5;
prop_cutout_radius = 35;
arm_thickness = 4;

// --- Main Assembly ---
union() {{
    // 1. Aerodynamic Rim (The "Frisbee")
    difference() {{
        // Outer Shell (NACA-ish profile approximated by scaled cylinder/sphere)
        rotate_extrude() 
            translate([outer_radius - 10, 0, 0]) 
            circle(r=10);
            
        // Inner Volume (Hollow)
        rotate_extrude() 
            translate([outer_radius - 10, 0, 0]) 
            circle(r=10 - {wall_thick});
    }}
    
    // 连接 rim to hub (4 Arms)
    for(i = [0 : 90 : 360]) {{
        rotate([0, 0, i])
        translate([hub_radius, -arm_thickness/2, -rim_height/4])
        cube([outer_radius - hub_radius - 10, arm_thickness, rim_height/2]);
    }}

    // 2. Central Avionics Hub
    cylinder(h=rim_height, r=hub_radius, center=true);
    
    // 3. Propeller Ducts (Integrated into structural mesh)
    // Actually, in a frisbee drone, props are usually INSIDE the disc area or central.
    // Let's create 4 mounting points inside the arms.
    for(i = [45 : 90 : 360]) {{
        rotate([0, 0, i])
        translate([outer_radius * 0.6, 0, 0])
        difference() {{
            cylinder(h=rim_height, r=prop_cutout_radius + 2, center=true);
            cylinder(h=rim_height+1, r=prop_cutout_radius, center=true); // Cutout
        }}
    }}
}}

// --- Physics Properties ---
// Mass Estimate: ~650g (Carbon Fiber)
// Inertia Tensor: Izz >> Ixx, Iyy (Stable Spin)
"""
    return code

if __name__ == "__main__":
    # Generate code
    scad = generate_frisbee_drone_scad()
    
    # Save to artifact
    output_path = os.path.join(os.getcwd(), "frisbee_drone.scad")
    with open(output_path, "w") as f:
        f.write(scad)
        
    print(f"Generated SCAD code at: {output_path}")
    print("\n--- PREVIEW ---\n")
    print(scad)
