import sys
import os
import json
import logging

# FIX PATH: Append backend directory to sys.path
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

# Setup Logging to capture "Agent Participation"
logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(name)s: %(message)s')
logger = logging.getLogger("DEMO_ORCHESTRATOR")

def run_demo():
    print("=== STARTING DEMO: MINIATURE NUCLEAR ENGINE ===")
    
    # 1. DESIGN AGENT (Mocked logic for specific intent)
    print("\n[STEP 1] DESIGN AGENT: Concept Generation")
    design_specs = {
        "name": "MiniStart-1",
        "type": "Nuclear Thermal Ricket (Drone Scale)",
        "fuel": "U-235",
        "core_radius_m": 0.15, # 15cm core (Miniature)
        "target_temp_k": 1200,
        "physics_domain": "NUCLEAR"
    }
    print(f"   > Proposing Desgin: {design_specs}")
    
    # 2. PHYSICS AGENT (Verification via Oracle)
    print("\n[STEP 2] PHYSICS AGENT: Feasibility Check (Oracle)")
    from agents.physics_oracle.physics_oracle import PhysicsOracle
    oracle = PhysicsOracle()
    
    # Check 1: Nuclear Criticality
    print("   > Querying Oracle (NUCLEAR)...")
    nuc_result = oracle.solve(
        query="Verify Criticality",
        domain="NUCLEAR",
        params={
            "type": "FISSION", # Required for NuclearAdapter
            "fuel_type": design_specs["fuel"],
            "radius": design_specs["core_radius_m"],
            "enrichment": 0.90 # High enrichment for miniature
        }
    )
    
    print(f"DEBUG: nuc_result = {nuc_result}")

    if nuc_result["status"] != "solved":
        print(f"   > [FAIL] Nuclear Check Failed: {nuc_result['message']}")
        return
        
    nuc_data = nuc_result # Adapter returns flat structure
    print(f"   > [PASS] Nuclear Status: {nuc_data.get('status', 'Unknown')}")
    print(f"   >        Power Output: {nuc_data.get('power_thermal_mw', 0):.2f} MW")
    
    # Check 2: Thermodynamics (Radiators)
    print("\n[STEP 3] THERMAL AGENT: Heat Management")
    print("   > Querying Oracle (THERMODYNAMICS)...")
    therm_result = oracle.solve(
        query="Size Radiators",
        domain="THERMODYNAMICS",
        params={
            "cycle": "BRAYTON",
            "T_hot": design_specs["target_temp_k"],
            "power_thermal_mw": nuc_data.get('power_thermal_mw', 10),
            "environment_temp_k": 250 # High altitude
        }
    )
    
    therm_data = therm_result
    print(f"   > [PASS] Efficiency: {therm_data.get('efficiency_real', 0)*100:.1f}%")
    print(f"   >        Waste Heat: {therm_data.get('power_waste_mw', 0):.2f} MW")
    print(f"   >        Radiator Area: {therm_data.get('radiator_area_m2', 0):.2f} m^2")

    # 3. GENERATIVE CAD (Writing the 3D Code)
    print("\n[STEP 4] CAD AGENT: 3D Model Generation")
    
    kcl_code = f"""
    // MINIATURE NUCLEAR ENGINE (Generated by BRICK CAD Agent)
    // Specs: Radius={design_specs['core_radius_m']}m, Temp={design_specs['target_temp_k']}K
    
    // 1. Reactor Core (Hexagonal Prism for Fuel Rods)
    const core_r = {design_specs['core_radius_m'] * 1000}; // mm
    const core_h = {design_specs['core_radius_m'] * 2000}; // mm
    
    const core = cylinder(r=core_r, h=core_h);
    
    // 2. Shielding (Tungsten Shell)
    const shield_r = core_r + 50;
    const shield = difference(
        cylinder(r=shield_r, h=core_h + 100),
        cylinder(r=core_r, h=core_h + 200) // Cutout
    );
    
    // 3. Nozzle (Rocket Exhaust)
    const nozzle = cylinder(r1=shield_r, r2=shield_r*0.4, h=300);
    
    // Assembly
    union() {{
        color([0.2, 0.2, 0.2]) render(shield);
        color([0, 1, 0]) translate([0,0,50]) render(core); // Green glow
        color([0.5, 0.5, 0.5]) translate([0,0,-300]) render(nozzle);
    }}
    """
    
    print("   > Generating KCL/OpenSCAD Code...")
    print(kcl_code)
    
    print("\n=== DEMO COMPLETE ===")

if __name__ == "__main__":
    run_demo()
