-- Run this in your Supabase SQL Editor to create the necessary tables

-- 1. Elements
CREATE TABLE IF NOT EXISTS elements (
    symbol TEXT PRIMARY KEY,
    atomic_number INTEGER,
    atomic_mass REAL,
    name TEXT,
    "group" TEXT, -- group is a reserved word
    density REAL
);

-- 2. Alloys
CREATE TABLE IF NOT EXISTS alloys (
    id TEXT PRIMARY KEY,
    name TEXT,
    category TEXT,
    composition JSONB, -- Store as JSON object e.g. {"Al": 98.0, "Cu": 2.0}
    yield_strength REAL,
    tensile_strength REAL,
    hardness_vickers REAL
);

-- 1. Components (Universal Catalog)
CREATE TABLE IF NOT EXISTS components (
    id TEXT PRIMARY KEY,
    category TEXT, -- 'motor', 'fastener', 'sensor', 'structural'
    name TEXT,
    description TEXT,
    
    -- Universal Physical Properties (Stochastic JSONB)
    -- Format: { "nominal": 10.0, "sigma": 0.5, "distribution": "normal", "unit": "g" }
    mass_g JSONB, 
    cost_usd JSONB, 
    
    -- Specialized Specs (The "Datasheet")
    -- Motor: { "kv": 100, "resistance": 0.05 }
    -- Screw: { "thread": "M3", "length": 10 }
    specs JSONB,
    
    -- 3D Generative Definition (Digital Twin Instructions)
    -- { "generator": "parametric_motor", "params": { "stator": 22, ... } }
    geometry_def JSONB,
    
    -- Simulation Behavior (Surrogate Models / Curves)
    behavior_model JSONB,
    
    -- Metadata (Ingestion Source)
    metadata JSONB, -- { "source": "mcmaster", "url": "...", "ingested_at": "..." }
    
    -- Vector Embedding for Semantic Search (Optional, for "find me a heavy motor")
    embedding vector(1536) -- Requires pgvector extension
);

-- 3. Compounds
CREATE TABLE IF NOT EXISTS compounds (
    id TEXT PRIMARY KEY,
    name TEXT,
    formula TEXT,
    molecular_weight REAL
);

-- 4. Material Properties (Temperature Dependent)
CREATE TABLE IF NOT EXISTS properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    material_id TEXT, -- FK to alloys.id or elements.symbol
    property_name TEXT, -- 'thermal_conductivity', 'specific_heat', etc.
    temperature REAL, -- Kelvin
    property_value REAL
);

-- 5. Monomers (Polymers)
CREATE TABLE IF NOT EXISTS monomers (
    id TEXT PRIMARY KEY,
    mw REAL,
    stiffness_gpa REAL,
    density_g_cc REAL,
    classification TEXT,
    base_strength_mpa REAL DEFAULT 30.0,
    alignment_bonus REAL DEFAULT 1.0,
    outgassing_compliant BOOLEAN DEFAULT TRUE,
    radiation_shielding_score INTEGER DEFAULT 50
);

-- 6. Ballistic Threats
CREATE TABLE IF NOT EXISTS ballistic_threats (
    id TEXT PRIMARY KEY,
    mass_g REAL,
    velocity_mps REAL,
    energy_j REAL
);

-- 7. Kinetics (Chemistry Simulation)
CREATE TABLE IF NOT EXISTS kinetics (
    material_family TEXT PRIMARY KEY,
    base_rate_mm_year REAL,
    ph_sensitivity REAL DEFAULT 0.0,
    ph_limit_low REAL,
    ph_limit_high REAL,
    amphoteric_factor REAL DEFAULT 1.0,
    q10_factor REAL DEFAULT 2.0
);

-- Enable Row Level Security (RLS) if needed, or leave public for now
-- ALTER TABLE elements ENABLE ROW LEVEL SECURITY;
-- (Default policies usually allow read/write if not configured, or deny all. Check your project settings.)
