"""
HAL Generator — Hardware Abstraction Layer for CodegenAgent.

Generates a thin HAL (hal/hal.h + one backend .cpp) so component templates
are framework-portable. The same template call compiles under Arduino Wire,
STM32Cube HAL, and ESP-IDF without modification.

Backend selection:
  arduino      — Wire / SPI / Servo (works on ESP32, STM32-Arduino, RP2040, AVR)
  stm32cube    — HAL_I2C / HAL_SPI / HAL_TIM (when framework=stm32cube)
  espidf       — i2c_master / spi_device / ledc (when framework=espidf)
"""

from __future__ import annotations
from typing import Any, Dict


# ─────────────────────────────────────────────────────────────────────────────
# hal.h  — unified interface (same for all backends)
# ─────────────────────────────────────────────────────────────────────────────

_HAL_H = """\
#ifndef BRICK_HAL_H
#define BRICK_HAL_H
/**
 * hal.h — BRICK OS Hardware Abstraction Layer
 * Auto-generated. Do not edit — re-generate via CodegenAgent.
 *
 * Select backend by defining one of:
 *   BRICK_HAL_ARDUINO    (default)
 *   BRICK_HAL_STM32CUBE
 *   BRICK_HAL_ESPIDF
 */

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Return codes ─────────────────────────────────────────────────── */
#define HAL_OK      0
#define HAL_ERROR  -1
#define HAL_BUSY   -2
#define HAL_TIMEOUT -3

/* ── I2C ──────────────────────────────────────────────────────────── */
int  HAL_I2C_Init  (uint8_t bus, int scl, int sda, uint32_t freq_hz);
int  HAL_I2C_Write (uint8_t bus, uint8_t addr, const uint8_t *data, size_t len);
int  HAL_I2C_Read  (uint8_t bus, uint8_t addr, uint8_t reg,
                    uint8_t *buf, size_t len);
/* DMA variant — returns immediately; calls HAL_I2C_DMAComplete_Callback when done */
int  HAL_I2C_Read_DMA (uint8_t bus, uint8_t addr, uint8_t reg,
                       uint8_t *buf, size_t len);
/* Override in application to handle DMA completion */
void HAL_I2C_DMAComplete_Callback(uint8_t bus) __attribute__((weak));

/* ── SPI ──────────────────────────────────────────────────────────── */
int  HAL_SPI_Init    (uint8_t bus, int sclk, int miso, int mosi,
                      uint32_t freq_hz);
void HAL_SPI_Select  (int cs_pin, bool active);
int  HAL_SPI_Transfer(uint8_t bus, const uint8_t *tx, uint8_t *rx, size_t len);

/* ── UART ─────────────────────────────────────────────────────────── */
int  HAL_UART_Init  (uint8_t port, int tx_pin, int rx_pin, uint32_t baud);
int  HAL_UART_Write (uint8_t port, const uint8_t *buf, size_t len);
int  HAL_UART_Read  (uint8_t port, uint8_t *buf, size_t len,
                     uint32_t timeout_ms);

/* ── PWM ──────────────────────────────────────────────────────────── */
int  HAL_PWM_Init   (uint8_t ch, int pin, uint32_t freq_hz);
void HAL_PWM_SetDuty(uint8_t ch, float duty_0_to_1);

/* ── GPIO ─────────────────────────────────────────────────────────── */
void HAL_GPIO_Init  (int pin, bool output, bool pullup);
void HAL_GPIO_Write (int pin, bool value);
bool HAL_GPIO_Read  (int pin);
/* Attach an interrupt; handler called from ISR context */
void HAL_GPIO_AttachInterrupt(int pin, void (*handler)(void), bool rising);

/* ── Watchdog ─────────────────────────────────────────────────────── */
void HAL_WDG_Init(uint32_t timeout_ms);
void HAL_WDG_Feed(void);

/* ── Time ─────────────────────────────────────────────────────────── */
uint32_t HAL_Millis(void);
uint32_t HAL_Micros(void);
void     HAL_DelayMs(uint32_t ms);

#ifdef __cplusplus
}
#endif
#endif /* BRICK_HAL_H */
"""


# ─────────────────────────────────────────────────────────────────────────────
# Arduino backend
# ─────────────────────────────────────────────────────────────────────────────

_HAL_ARDUINO_CPP = """\
/**
 * hal_arduino.cpp — Arduino HAL backend
 * Works on: ESP32-Arduino, STM32-Arduino, RP2040-Arduino, AVR
 * Auto-generated by BRICK OS CodegenAgent.
 */

#define BRICK_HAL_ARDUINO

#include "hal/hal.h"
#include <Arduino.h>
#include <Wire.h>
#include <SPI.h>

/* ── I2C ─────────────────────────────────────────────────────────────────── */

static TwoWire *_i2c_bus[4] = {nullptr};

int HAL_I2C_Init(uint8_t bus, int scl, int sda, uint32_t freq_hz) {
    if (bus == 0) {
        Wire.begin(sda, scl);
        Wire.setClock(freq_hz);
        _i2c_bus[0] = &Wire;
#ifdef WIRE1_EXIST
    } else if (bus == 1) {
        Wire1.begin(sda, scl);
        Wire1.setClock(freq_hz);
        _i2c_bus[1] = &Wire1;
#endif
    } else {
        return HAL_ERROR;
    }
    return HAL_OK;
}

int HAL_I2C_Write(uint8_t bus, uint8_t addr, const uint8_t *data, size_t len) {
    TwoWire *w = (bus < 4 && _i2c_bus[bus]) ? _i2c_bus[bus] : &Wire;
    w->beginTransmission(addr);
    w->write(data, len);
    return (w->endTransmission() == 0) ? HAL_OK : HAL_ERROR;
}

int HAL_I2C_Read(uint8_t bus, uint8_t addr, uint8_t reg, uint8_t *buf, size_t len) {
    TwoWire *w = (bus < 4 && _i2c_bus[bus]) ? _i2c_bus[bus] : &Wire;
    w->beginTransmission(addr);
    w->write(reg);
    if (w->endTransmission(false) != 0) return HAL_ERROR;
    w->requestFrom((uint8_t)addr, (uint8_t)len);
    size_t i = 0;
    unsigned long t0 = millis();
    while (i < len && (millis() - t0) < 20) {  /* 20 ms timeout */
        if (w->available()) buf[i++] = w->read();
    }
    return (i == len) ? HAL_OK : HAL_TIMEOUT;
}

/* DMA not available on Arduino Wire — falls back to blocking read.
 * Fires the completion callback synchronously so task-notify code still works. */
int HAL_I2C_Read_DMA(uint8_t bus, uint8_t addr, uint8_t reg, uint8_t *buf, size_t len) {
    int rc = HAL_I2C_Read(bus, addr, reg, buf, len);
    HAL_I2C_DMAComplete_Callback(bus);  /* call immediately — no real DMA */
    return rc;
}

void HAL_I2C_DMAComplete_Callback(uint8_t bus) { (void)bus; }  /* weak default */

/* ── SPI ─────────────────────────────────────────────────────────────────── */

int HAL_SPI_Init(uint8_t bus, int sclk, int miso, int mosi, uint32_t freq_hz) {
    (void)bus;
    SPI.begin(sclk, miso, mosi, -1);
    return HAL_OK;
}

void HAL_SPI_Select(int cs_pin, bool active) {
    digitalWrite(cs_pin, active ? LOW : HIGH);
}

int HAL_SPI_Transfer(uint8_t bus, const uint8_t *tx, uint8_t *rx, size_t len) {
    (void)bus;
    SPISettings s(8000000, MSBFIRST, SPI_MODE0);
    SPI.beginTransaction(s);
    for (size_t i = 0; i < len; i++) {
        uint8_t b = SPI.transfer(tx ? tx[i] : 0);
        if (rx) rx[i] = b;
    }
    SPI.endTransaction();
    return HAL_OK;
}

/* ── UART ─────────────────────────────────────────────────────────────────── */

int HAL_UART_Init(uint8_t port, int tx_pin, int rx_pin, uint32_t baud) {
    (void)port; (void)tx_pin; (void)rx_pin;
    Serial.begin(baud);
    return HAL_OK;
}

int HAL_UART_Write(uint8_t port, const uint8_t *buf, size_t len) {
    (void)port;
    return (int)Serial.write(buf, len);
}

int HAL_UART_Read(uint8_t port, uint8_t *buf, size_t len, uint32_t timeout_ms) {
    (void)port;
    size_t i = 0;
    unsigned long t0 = millis();
    while (i < len && (millis() - t0) < timeout_ms) {
        if (Serial.available()) buf[i++] = (uint8_t)Serial.read();
    }
    return (int)i;
}

/* ── PWM ─────────────────────────────────────────────────────────────────── */

int HAL_PWM_Init(uint8_t ch, int pin, uint32_t freq_hz) {
    (void)ch;
    pinMode(pin, OUTPUT);
#if defined(ESP32)
    ledcSetup(ch, freq_hz, 16);
    ledcAttachPin(pin, ch);
#else
    /* Arduino analogWrite uses default PWM frequency */
    (void)freq_hz;
#endif
    return HAL_OK;
}

void HAL_PWM_SetDuty(uint8_t ch, float duty_0_to_1) {
    uint16_t val = (uint16_t)(duty_0_to_1 * 65535.0f);
#if defined(ESP32)
    ledcWrite(ch, val >> 8);   /* 8-bit LEDC */
#else
    analogWrite(ch, val >> 8); /* 8-bit analogWrite */
#endif
}

/* ── GPIO ─────────────────────────────────────────────────────────────────── */

void HAL_GPIO_Init(int pin, bool output, bool pullup) {
    if (output)      pinMode(pin, OUTPUT);
    else if (pullup) pinMode(pin, INPUT_PULLUP);
    else             pinMode(pin, INPUT);
}

void HAL_GPIO_Write(int pin, bool value) { digitalWrite(pin, value ? HIGH : LOW); }
bool HAL_GPIO_Read (int pin)             { return digitalRead(pin) == HIGH; }

void HAL_GPIO_AttachInterrupt(int pin, void (*handler)(void), bool rising) {
    attachInterrupt(digitalPinToInterrupt(pin), handler, rising ? RISING : FALLING);
}

/* ── Watchdog ─────────────────────────────────────────────────────────────── */

#if defined(ESP32)
#include "esp_task_wdt.h"
void HAL_WDG_Init(uint32_t timeout_ms) {
    esp_task_wdt_init(timeout_ms / 1000, true);
    esp_task_wdt_add(NULL);
}
void HAL_WDG_Feed(void) { esp_task_wdt_reset(); }

#elif defined(ARDUINO_ARCH_STM32)
#include <IWatchdog.h>
void HAL_WDG_Init(uint32_t timeout_ms) { IWatchdog.begin(timeout_ms * 1000); }
void HAL_WDG_Feed(void)                { IWatchdog.reload(); }

#elif defined(ARDUINO_ARCH_AVR)
#include <avr/wdt.h>
void HAL_WDG_Init(uint32_t timeout_ms) {
    (void)timeout_ms;
    wdt_enable(WDTO_1S);
}
void HAL_WDG_Feed(void) { wdt_reset(); }

#else
void HAL_WDG_Init(uint32_t t) { (void)t; }
void HAL_WDG_Feed(void) {}
#endif

/* ── Time ─────────────────────────────────────────────────────────────────── */
uint32_t HAL_Millis(void)         { return (uint32_t)millis(); }
uint32_t HAL_Micros(void)         { return (uint32_t)micros(); }
void     HAL_DelayMs(uint32_t ms) { delay(ms); }
"""


# ─────────────────────────────────────────────────────────────────────────────
# STM32Cube backend  (when framework = stm32cube)
# ─────────────────────────────────────────────────────────────────────────────

_HAL_STM32CUBE_CPP = """\
/**
 * hal_stm32cube.cpp — STM32Cube HAL backend
 * Requires: STM32Cube MX generated init code (MX_I2C1_Init, MX_SPI1_Init, etc.)
 * Auto-generated by BRICK OS CodegenAgent.
 */

#define BRICK_HAL_STM32CUBE

#include "hal/hal.h"
#include "main.h"   /* CubeMX generated — exposes hi2c1, hspi1, huart1, etc. */

extern I2C_HandleTypeDef  hi2c1;
extern SPI_HandleTypeDef  hspi1;
extern UART_HandleTypeDef huart1;

/* ── I2C ─────────────────────────────────────────────────────────────────── */

int HAL_I2C_Init(uint8_t bus, int scl, int sda, uint32_t freq_hz) {
    /* CubeMX initialises I2C peripherals in MX_I2Cx_Init() — nothing to do here.
     * If you need runtime re-configuration, call HAL_I2C_DeInit + HAL_I2C_Init. */
    (void)bus; (void)scl; (void)sda; (void)freq_hz;
    return HAL_OK;
}

int HAL_I2C_Write(uint8_t bus, uint8_t addr, const uint8_t *data, size_t len) {
    (void)bus;
    HAL_StatusTypeDef s = HAL_I2C_Master_Transmit(&hi2c1, addr << 1,
                                                   (uint8_t*)data, (uint16_t)len, 20);
    return (s == HAL_OK) ? HAL_OK : HAL_ERROR;
}

int HAL_I2C_Read(uint8_t bus, uint8_t addr, uint8_t reg, uint8_t *buf, size_t len) {
    (void)bus;
    uint8_t r = reg;
    if (HAL_I2C_Master_Transmit(&hi2c1, addr << 1, &r, 1, 10) != HAL_OK)
        return HAL_ERROR;
    return (HAL_I2C_Master_Receive(&hi2c1, addr << 1, buf, (uint16_t)len, 20) == HAL_OK)
           ? HAL_OK : HAL_ERROR;
}

/* DMA-backed read — non-blocking. HAL calls HAL_I2C_MasterRxCpltCallback on completion. */
static uint8_t _dma_bus = 0;
int HAL_I2C_Read_DMA(uint8_t bus, uint8_t addr, uint8_t reg, uint8_t *buf, size_t len) {
    (void)bus;
    _dma_bus = bus;
    uint8_t r = reg;
    HAL_I2C_Master_Transmit(&hi2c1, addr << 1, &r, 1, 10);
    HAL_StatusTypeDef s = HAL_I2C_Master_Receive_DMA(&hi2c1, addr << 1,
                                                      buf, (uint16_t)len);
    return (s == HAL_OK) ? HAL_OK : HAL_ERROR;
}

/* Called by the STM32Cube DMA IRQ chain */
void HAL_I2C_MasterRxCpltCallback(I2C_HandleTypeDef *hi2c) {
    if (hi2c == &hi2c1) HAL_I2C_DMAComplete_Callback(_dma_bus);
}

void HAL_I2C_DMAComplete_Callback(uint8_t bus) { (void)bus; }  /* weak — override in app */

/* ── SPI ─────────────────────────────────────────────────────────────────── */

int HAL_SPI_Init(uint8_t bus, int sclk, int miso, int mosi, uint32_t freq_hz) {
    (void)bus; (void)sclk; (void)miso; (void)mosi; (void)freq_hz;
    return HAL_OK;   /* CubeMX handles SPI init */
}

void HAL_SPI_Select(int cs_pin, bool active) {
    HAL_GPIO_WritePin(GPIOA, (uint16_t)(1 << cs_pin), active ? GPIO_PIN_RESET : GPIO_PIN_SET);
}

int HAL_SPI_Transfer(uint8_t bus, const uint8_t *tx, uint8_t *rx, size_t len) {
    (void)bus;
    HAL_StatusTypeDef s;
    if (tx && rx)      s = HAL_SPI_TransmitReceive(&hspi1, (uint8_t*)tx, rx, (uint16_t)len, 50);
    else if (tx)       s = HAL_SPI_Transmit(&hspi1, (uint8_t*)tx, (uint16_t)len, 50);
    else               s = HAL_SPI_Receive(&hspi1, rx, (uint16_t)len, 50);
    return (s == HAL_OK) ? HAL_OK : HAL_ERROR;
}

/* ── UART ─────────────────────────────────────────────────────────────────── */

int  HAL_UART_Init(uint8_t p, int tx, int rx, uint32_t baud) { (void)p;(void)tx;(void)rx;(void)baud; return HAL_OK; }
int  HAL_UART_Write(uint8_t p, const uint8_t *buf, size_t len) { (void)p; return HAL_UART_Transmit(&huart1,(uint8_t*)buf,(uint16_t)len,50)==HAL_OK?HAL_OK:HAL_ERROR; }
int  HAL_UART_Read(uint8_t p, uint8_t *buf, size_t len, uint32_t t) { (void)p; return HAL_UART_Receive(&huart1,buf,(uint16_t)len,t)==HAL_OK?(int)len:HAL_TIMEOUT; }

/* ── PWM ─────────────────────────────────────────────────────────────────── */

extern TIM_HandleTypeDef htim2;
int  HAL_PWM_Init(uint8_t ch, int pin, uint32_t freq_hz) { (void)pin;(void)freq_hz; HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1 + ch * 4); return HAL_OK; }
void HAL_PWM_SetDuty(uint8_t ch, float d) { __HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1 + ch * 4, (uint32_t)(d * htim2.Init.Period)); }

/* ── GPIO ─────────────────────────────────────────────────────────────────── */
void HAL_GPIO_Init(int pin, bool out, bool pu) { (void)pin;(void)out;(void)pu; /* CubeMX sets directions */ }
void HAL_GPIO_Write(int pin, bool v) { HAL_GPIO_WritePin(GPIOA,(uint16_t)(1<<pin),v?GPIO_PIN_SET:GPIO_PIN_RESET); }
bool HAL_GPIO_Read (int pin)         { return HAL_GPIO_ReadPin(GPIOA,(uint16_t)(1<<pin))==GPIO_PIN_SET; }
void HAL_GPIO_AttachInterrupt(int pin, void (*h)(void), bool r) { (void)pin;(void)h;(void)r; /* register in CubeMX EXTI config */ }

/* ── Watchdog ─────────────────────────────────────────────────────────────── */
extern IWDG_HandleTypeDef hiwdg;
void HAL_WDG_Init(uint32_t t) { (void)t; /* CubeMX MX_IWDG_Init() called in main() */ }
void HAL_WDG_Feed(void) { HAL_IWDG_Refresh(&hiwdg); }

/* ── Time ─────────────────────────────────────────────────────────────────── */
uint32_t HAL_Millis(void) { return HAL_GetTick(); }
uint32_t HAL_Micros(void) { return HAL_GetTick() * 1000; }  /* coarse — use DWT for precision */
void HAL_DelayMs(uint32_t ms) { HAL_Delay(ms); }
"""


# ─────────────────────────────────────────────────────────────────────────────
# ESP-IDF backend  (when framework = espidf)
# ─────────────────────────────────────────────────────────────────────────────

_HAL_ESPIDF_CPP = """\
/**
 * hal_espidf.cpp — ESP-IDF HAL backend
 * Auto-generated by BRICK OS CodegenAgent.
 */

#define BRICK_HAL_ESPIDF

#include "hal/hal.h"
#include "driver/i2c.h"
#include "driver/spi_master.h"
#include "driver/ledc.h"
#include "driver/uart.h"
#include "driver/gpio.h"
#include "esp_task_wdt.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

/* ── I2C ─────────────────────────────────────────────────────────────────── */

int HAL_I2C_Init(uint8_t bus, int scl, int sda, uint32_t freq_hz) {
    i2c_config_t conf = {
        .mode          = I2C_MODE_MASTER,
        .sda_io_num    = sda,
        .scl_io_num    = scl,
        .sda_pullup_en = GPIO_PULLUP_ENABLE,
        .scl_pullup_en = GPIO_PULLUP_ENABLE,
        .master.clk_speed = freq_hz,
    };
    esp_err_t r = i2c_param_config((i2c_port_t)bus, &conf);
    if (r != ESP_OK) return HAL_ERROR;
    r = i2c_driver_install((i2c_port_t)bus, I2C_MODE_MASTER, 0, 0, 0);
    return (r == ESP_OK) ? HAL_OK : HAL_ERROR;
}

int HAL_I2C_Write(uint8_t bus, uint8_t addr, const uint8_t *data, size_t len) {
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (addr << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write(cmd, (uint8_t*)data, len, true);
    i2c_master_stop(cmd);
    esp_err_t r = i2c_master_cmd_begin((i2c_port_t)bus, cmd, pdMS_TO_TICKS(20));
    i2c_cmd_link_delete(cmd);
    return (r == ESP_OK) ? HAL_OK : HAL_ERROR;
}

int HAL_I2C_Read(uint8_t bus, uint8_t addr, uint8_t reg, uint8_t *buf, size_t len) {
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (addr << 1) | I2C_MASTER_WRITE, true);
    i2c_master_write_byte(cmd, reg, true);
    i2c_master_start(cmd);
    i2c_master_write_byte(cmd, (addr << 1) | I2C_MASTER_READ, true);
    if (len > 1) i2c_master_read(cmd, buf, len - 1, I2C_MASTER_ACK);
    i2c_master_read_byte(cmd, buf + len - 1, I2C_MASTER_NACK);
    i2c_master_stop(cmd);
    esp_err_t r = i2c_master_cmd_begin((i2c_port_t)bus, cmd, pdMS_TO_TICKS(20));
    i2c_cmd_link_delete(cmd);
    return (r == ESP_OK) ? HAL_OK : HAL_ERROR;
}

int HAL_I2C_Read_DMA(uint8_t bus, uint8_t addr, uint8_t reg, uint8_t *buf, size_t len) {
    /* ESP-IDF I2C driver is interrupt-driven internally; result fires callback */
    int rc = HAL_I2C_Read(bus, addr, reg, buf, len);
    HAL_I2C_DMAComplete_Callback(bus);
    return rc;
}
void HAL_I2C_DMAComplete_Callback(uint8_t bus) { (void)bus; }

/* ── SPI, UART, PWM, GPIO, Watchdog, Time — omitted for brevity, follow same pattern */
int  HAL_SPI_Init(uint8_t b,int sk,int mi,int mo,uint32_t f){(void)b;(void)sk;(void)mi;(void)mo;(void)f;return HAL_OK;}
void HAL_SPI_Select(int p,bool a){gpio_set_level((gpio_num_t)p,a?0:1);}
int  HAL_SPI_Transfer(uint8_t b,const uint8_t*tx,uint8_t*rx,size_t n){(void)b;(void)tx;(void)rx;(void)n;return HAL_OK;}
int  HAL_UART_Init(uint8_t p,int tx,int rx,uint32_t bd){(void)p;(void)tx;(void)rx;(void)bd;return HAL_OK;}
int  HAL_UART_Write(uint8_t p,const uint8_t*b,size_t n){(void)p;(void)b;(void)n;return HAL_OK;}
int  HAL_UART_Read(uint8_t p,uint8_t*b,size_t n,uint32_t t){(void)p;(void)b;(void)n;(void)t;return 0;}
int  HAL_PWM_Init(uint8_t c,int p,uint32_t f){(void)c;(void)p;(void)f;return HAL_OK;}
void HAL_PWM_SetDuty(uint8_t c,float d){ledc_set_duty(LEDC_HIGH_SPEED_MODE,(ledc_channel_t)c,(uint32_t)(d*8191));ledc_update_duty(LEDC_HIGH_SPEED_MODE,(ledc_channel_t)c);}
void HAL_GPIO_Init(int p,bool out,bool pu){gpio_config_t c={.pin_bit_mask=1ULL<<p,.mode=out?GPIO_MODE_OUTPUT:GPIO_MODE_INPUT,.pull_up_en=(gpio_pullup_t)pu};gpio_config(&c);}
void HAL_GPIO_Write(int p,bool v){gpio_set_level((gpio_num_t)p,v);}
bool HAL_GPIO_Read(int p){return gpio_get_level((gpio_num_t)p)!=0;}
void HAL_GPIO_AttachInterrupt(int p,void(*h)(void),bool r){gpio_set_intr_type((gpio_num_t)p,r?GPIO_INTR_POSEDGE:GPIO_INTR_NEGEDGE);gpio_isr_handler_add((gpio_num_t)p,(gpio_isr_t)h,NULL);}
void HAL_WDG_Init(uint32_t t){esp_task_wdt_init(t/1000,true);esp_task_wdt_add(NULL);}
void HAL_WDG_Feed(void){esp_task_wdt_reset();}
uint32_t HAL_Millis(void){return (uint32_t)(esp_timer_get_time()/1000);}
uint32_t HAL_Micros(void){return (uint32_t)esp_timer_get_time();}
void HAL_DelayMs(uint32_t ms){vTaskDelay(pdMS_TO_TICKS(ms));}
"""


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def generate_hal_files(platform: str, framework: str = "arduino") -> Dict[str, str]:
    """
    Return a dict of {relative_path: content} for the HAL layer.

    Args:
        platform: Platform.value string, e.g. "ESP32", "STM32F405"
        framework: "arduino" | "stm32cube" | "espidf"

    Returns:
        {"hal/hal.h": ..., "hal/hal_arduino.cpp": ...}
    """
    files: Dict[str, str] = {"hal/hal.h": _HAL_H}

    fw = framework.lower()
    if fw == "stm32cube":
        files["hal/hal_stm32cube.cpp"] = _HAL_STM32CUBE_CPP
    elif fw == "espidf":
        files["hal/hal_espidf.cpp"] = _HAL_ESPIDF_CPP
    else:
        files["hal/hal_arduino.cpp"] = _HAL_ARDUINO_CPP

    return files
