// MINIATURE NUCLEAR ENGINE (Generated by BRICK CAD Agent)
// Specs: Radius=0.15m, Temp=1200K
$fn = 64; // Resolution

// 1. Parameters
core_r = 150.0; // mm
core_h = 300.0; // mm
shield_thickness = 50.0;
shield_r = core_r + shield_thickness;

// Assembly
union() {
    // 2. Shielding (Tungsten Shell - Dark Grey)
    color([0.2, 0.2, 0.2])
    difference() {
        cylinder(r = shield_r, h = core_h + 100, center = true);
        // Hollow out the core area
        cylinder(r = core_r, h = core_h + 200, center = true);
    }

    // 1. Reactor Core (Uranium Fuel - Glowing Green)
    color([0, 1, 0, 0.8]) // Transparent green
    cylinder(r = core_r, h = core_h, center = true);

    // 3. Nozzle (Rocket Exhaust - Metal)
    color([0.5, 0.5, 0.5])
    translate([0, 0, -(core_h / 2 + 150)])
    cylinder(r1 = shield_r, r2 = shield_r * 0.4, h = 300, center = true);
}
